'use strict'

const fs = require('node:fs')
const path = require('node:path')

const rfc = require('./rfc.js')

const HEADER = '<!-- This file is generated by `npm run rfc:index`. Do not edit by hand. -->'

const STATUS_ORDER = ['accepted', 'implemented', 'withdrawn']

const STATUS_LABEL = {
  accepted: 'Accepted',
  implemented: 'Implemented',
  withdrawn: 'Withdrawn',
}

function generate (repoRoot, { now = new Date() } = {}) {
  const entries = []
  for (const entry of rfc.listRfcs(repoRoot)) {
    if (!entry.parsed || entry.parsed.number === 0) {
      continue
    }
    let parsed
    try {
      parsed = rfc.parseRfc(entry.absPath)
    } catch (err) {
      throw new Error(`Failed to parse ${entry.relPath}: ${err.message}`)
    }
    entries.push({
      ...entry,
      data: parsed.data ?? {},
    })
  }

  const buckets = { accepted: [], implemented: [], withdrawn: [] }
  for (const entry of entries) {
    buckets[entry.folder].push(entry)
  }
  for (const list of Object.values(buckets)) {
    list.sort((a, b) => b.parsed.number - a.parsed.number)
  }

  const lines = []
  lines.push(HEADER)
  lines.push('')
  lines.push('# RFC index')
  lines.push('')
  lines.push(
    `Generated ${rfc.todayIso(now)}. See [README.md](./README.md) for the RFC process.`
  )
  lines.push('')

  for (const folder of STATUS_ORDER) {
    const list = buckets[folder]
    lines.push(`## ${STATUS_LABEL[folder]} (${list.length})`)
    lines.push('')
    if (list.length === 0) {
      lines.push('_None yet._')
      lines.push('')
      continue
    }
    lines.push('| # | Title | Created | Accepted | Implemented | Withdrawn | Implementation |')
    lines.push('| - | ----- | ------- | -------- | ----------- | --------- | -------------- |')
    for (const entry of list) {
      const num = rfc.paddedNumber(entry.parsed.number)
      const title = entry.data.title?.trim() || rfc.deriveTitleFromSlug(entry.parsed.slug)
      const link = `[${num}](./${entry.relPath})`
      const titleCell = escapeCell(title)
      const createdCell = formatDate(entry.data.created)
      const acceptedCell = formatDate(entry.data.accepted_at)
      const implementedCell = formatDate(entry.data.implemented_at)
      const withdrawnCell = formatDate(entry.data.withdrawn_at)
      const implCell = formatImplementation(entry.data.implementation)
      lines.push(
        `| ${link} | ${titleCell} | ${createdCell} | ${acceptedCell} | ${implementedCell} | ${withdrawnCell} | ${implCell} |`
      )
    }
    lines.push('')
  }

  return lines.join('\n').replace(/\n+$/, '\n')
}

function write (repoRoot, opts = {}) {
  const content = generate(repoRoot, opts)
  const outPath = path.join(repoRoot, 'INDEX.md')
  fs.writeFileSync(outPath, content)
  return outPath
}

function formatDate (value) {
  if (!value) {
    return '—'
  }
  return String(value)
}

function formatImplementation (value) {
  if (!value) {
    return '—'
  }
  const str = String(value).trim()
  const ghRef = str.match(/^([\w.-]+)\/([\w.-]+)#(\d+)$/)
  if (ghRef) {
    return `[${str}](https://github.com/${ghRef[1]}/${ghRef[2]}/pull/${ghRef[3]})`
  }
  if (/^https?:\/\//.test(str)) {
    return `[link](<${str}>)`
  }
  return escapeCell(str)
}

function escapeCell (text) {
  return String(text)
    .replace(/\\/g, '\\\\')
    .replace(/\|/g, '\\|')
    .replace(/\n+/g, ' ')
    .trim()
}

module.exports = {
  generate,
  write,
}
